os:
  - osx

language: node_js

node_js:
  - "0.11"
  - "0.10"  

install:
  - sudo wget https://github.com/boot2docker/osx-installer/releases/download/v1.2.0/Boot2Docker-1.2.0.pkg
  - sudo installer -pkg Boot2Docker-1.2.0.pkg -target ./
  - sudo boot2docker init
  - sudo boot2docker start
  - sudo boot2docker ip
  - sudo export  DOCKER_HOST=tcp://192.168.59.103:2375
  - sudo bash docker-setup.sh

script:
  - npm run-script lint
  - npm run-script test
