install:
  - mount
  - curl https://raw.githubusercontent.com/matthewfl/travis-docker/master/strap | source /dev/stdin

script:
  - docker run -i -t  -P --name postgres -d nachiket/postgres
  - docker run --name apache_borrowed -p 80:80 -p 443:443 -d eboraas/apache
  - docker run -p 32322:32322 -p 43191:43191 -p 8888:8888 -ti --link postgres:postgres --link apache_borrowed:apache --name noit nachiket/noit

script:
  - npm run-script lint
  - npm run-script test
