language: node_js
node_js:
  - "0.10"
  - "0.11"
install:
  - sudo apt-get update
  - sudo apt-get install docker.io -y
  - sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
  - sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
  - apt-get install apt-transport-https -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo sh -c "echo deb https://get.docker.io/ubuntu docker main/etc/apt/sources.list.d/docker.list"
  - sudo apt-get install lxc-docker -y
  - sudo docker -d
  - sudo sleep 5
  - sudo docker ps
  - sudo bash docker-setup.sh
script:
  - npm run-script lint
  - npm run-script test
